Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using PgBookStore.Data;
using PgBookStore.Models;
using System.Linq;

namespace PgBookStore.Controllers
{
    public class AuthorController : Controller
    {
        private readonly ApplicationDbContext db;
        
        public AuthorController(ApplicationDbContext dbContext)
        {
            db = dbContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var items = db.Authors.Select(p => p);

            return View(items);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Author item)
        {
            if(ModelState.IsValid) {
                db.Add(item);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var item = db.Authors.SingleOrDefault(p => p.AuthorID.Equals(id));
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("AuthorID,Name,Email")] Author item)
        {
            if(ModelState.IsValid) {
                db.Update(item);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if(ModelState.IsValid) {
                var item = db.Authors.Find(id);
                db.Authors.Remove(item);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

Controllers/BookController.cs
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using PgBookStore.Models;
using PgBookStore.Data;

namespace PgBookStore.Controllers
{
    public class BookController : Controller
    {
        private readonly ApplicationDbContext db;
        private IWebHostEnvironment _environment;

        public BookController(ApplicationDbContext dbContext, IWebHostEnvironment environment)
        {
            db = dbContext;
            _environment = environment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var bookList = db.Books
                .Include(c => c.Category)
                .Include(ba => ba.BooksAuthors)
                .ThenInclude(a => a.Author)
                .ToList();
            
            IList<BookViewModel> items = new List<BookViewModel>();
            foreach (Book book in bookList)
            {
                BookViewModel item = new BookViewModel();
                item.ISBN = book.BookID;
                item.Title = book.Title;
                item.Photo = book.Photo;
                item.PublishDate = book.PublishDate;
                item.Price = book.Price;
                item.Quantity = book.Quantity;
                item.CategoryName = book.Category.Name;

                string authorNameList = string.Empty;
                var booksAuthorsList = book.BooksAuthors;
                foreach (BookAuthor bookAuthor in booksAuthorsList)
                {
                    var author = bookAuthor.Author;
                    authorNameList = authorNameList + author.Name + ", ";
                }
                item.AuthorNames = authorNameList.Substring(0, authorNameList.Length - 2);

                items.Add(item);
            }

            return View(items);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(db.Catetories.ToList(), "CategoryID", "Name");
            ViewBag.Authors = new MultiSelectList(db.Authors.ToList(), "AuthorID", "Name");

            return View();
        }

        [HttpPost]
        public IActionResult Create(BookFormViewModel item)
        {
            if(ModelState.IsValid) {
                Book book = new Book();
                book.BookID = item.ISBN;
                book.CategoryID = item.CategoryID;
                book.Title = item.Title;
                book.PublishDate = item.PublishDate;
                book.Price = item.Price;
                book.Quantity = item.Quantity;

                foreach (int authorId in item.AuthorIDs)
                {
                    BookAuthor bookAuthor = new BookAuthor();
                    bookAuthor.BookID = item.ISBN;
                    bookAuthor.AuthorID = authorId;

                    db.Add(bookAuthor);
                }
                
                if (item.Photo != null) {
                    var file = item.Photo;
                    var uploads = Path.Combine(_environment.WebRootPath, "upload");
                    //uniqueFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
                    if (file.Length > 0) {
                        using (var fileStream = new FileStream(Path.Combine(uploads, file.FileName), FileMode.Create)){
                            file.CopyTo(fileStream);
                        }
                    }
                    book.Photo = file.FileName;
                }

                db.Add(book);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ViewBag.Categories = new SelectList(db.Catetories.ToList(), "CategoryID", "Name");
            ViewBag.Authors = new MultiSelectList(db.Authors.ToList(), "AuthorID", "Name");

            var book = db.Books.SingleOrDefault(p => p.BookID.Equals(id));
            BookFormViewModel item = new BookFormViewModel();
            item.ISBN   = book.BookID;
            item.Title  = book.Title;
            item.PublishDate    = book.PublishDate;
            item.Price  = book.Price;
            item.Quantity   = book.Quantity;
            item.CategoryID = book.CategoryID;

            var authorList  = db.BookAuthors.Where(p => p.BookID.Equals(book.BookID)).ToList();
            List<int> authors = new List<int>();
            foreach (BookAuthor bookAuthor in authorList)
            {
                authors.Add(bookAuthor.AuthorID);
            }
            item.AuthorIDs  = authors.ToArray();

            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("ISBN,CategoryID,Title,Photo,PublishDate,Price,Quantity,AuthorIDs")] BookFormViewModel item)
        {
            if(ModelState.IsValid) {
                db.BookAuthors.RemoveRange(db.BookAuthors.Where(p => p.BookID.Equals(item.ISBN)));
                db.SaveChanges();

                Book book = db.Books.SingleOrDefault(p => p.BookID.Equals(item.ISBN));
                book.CategoryID = item.CategoryID;
                book.Title = item.Title;
                book.PublishDate = item.PublishDate;
                book.Price = item.Price;
                book.Quantity = item.Quantity;
                
                if (item.Photo != null) {
                    var file = item.Photo;
                    var uploads = Path.Combine(_environment.WebRootPath, "upload");
                    if (file.Length > 0) {
                        using(var fileStream = new FileStream(Path.Combine(uploads, file.FileName), FileMode.Create)) {
                            file.CopyTo(fileStream);
                        }
                    }
                    book.Photo = file.FileName;
                }

                db.Update(book);

                foreach (int authorId in item.AuthorIDs)
                {
                    BookAuthor bookAuthor = new BookAuthor();
                    bookAuthor.BookID = item.ISBN;
                    bookAuthor.AuthorID = authorId;

                    db.Add(bookAuthor);
                }

                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (ModelState.IsValid) {
                var item = db.Books.Find(id);
                db.BookAuthors.RemoveRange(db.BookAuthors.Where(p => p.BookID.Equals(item.BookID)));
                db.SaveChanges();

                db.Books.Remove(item);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

Controllers/RoleController.cs
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PgBookStore.Models;
using System.Threading.Tasks;

namespace PgBookStore.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<ApplicationRole> db;
        
        public RoleController(RoleManager<ApplicationRole> roleManager)
        {
            db = roleManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var items = new List<RoleViewModel>();
            items = db.Roles.Select(r => new RoleViewModel
            {
                RoleID = r.Id,
                RoleName = r.Name,
                Description = r.Description
            }).ToList();

            return View(items);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel item)
        {
            if (ModelState.IsValid) {
                ApplicationRole role = new ApplicationRole();
                role.Id = item.RoleID;
                role.Name = item.RoleName;
                role.Description = item.Description;

                var result = await db.CreateAsync(role);

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            RoleViewModel item = new RoleViewModel();
            ApplicationRole role = await db.FindByIdAsync(id);
            if (role != null) {
                item.RoleID = role.Id;
                item.RoleName = role.Name;
                item.Description = role.Description;
            }
            return View(item);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("RoleID,RoleName,Description")] RoleViewModel item)
        {
            if (ModelState.IsValid) {
                ApplicationRole role = await db.FindByIdAsync(item.RoleID);
                if (role != null) {
                    role.Id = item.RoleID;
                    role.Name = item.RoleName;
                    role.Description = item.Description;

                    var result = await db.UpdateAsync(role);
                }

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (ModelState.IsValid) {
                ApplicationRole role = await db.FindByIdAsync(id);
                var result = await db.DeleteAsync(role);

                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

Controllers/UserController.cs
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PgBookStore.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PgBookStore.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<ApplicationRole> roleManager;

        public UserController(UserManager<ApplicationUser> userManager, RoleManager<ApplicationRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var items = new List<UserViewModel>();
            var userList = userManager.Users.ToList();
            foreach (var user in userList)
            {
                var item = new UserViewModel();
                item.UserName = user.UserName;
                item.Email = user.Email;
                item.FullName = user.FullName;

                string roleNameList = string.Empty;
                var roleList = await userManager.GetRolesAsync(user);
                foreach (var role in roleList)
                {
                    roleNameList = roleNameList + role + ", ";                    
                }
                item.RoleName = roleNameList.Substring(0, roleNameList.Length - 2);

                items.Add(item);
            }

            return View(items);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Roles = new MultiSelectList(roleManager.Roles.ToList(), "Name","NormalizedName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserCreateFormViewModel item)
        {
            ViewBag.Roles = new MultiSelectList(roleManager.Roles.ToList(), "Name", "NormalizedName"); 

            if(ModelState.IsValid){
                ApplicationUser user = new ApplicationUser();
                user.FullName = item.FullName;
                user.UserName = item.UserName;
                user.Email = item.Email;
                IdentityResult result = await userManager.CreateAsync(user, item.Password);
                
                if (result.Succeeded) {
                    result = await userManager.AddToRolesAsync(user, item.RoleID);
                    if(result.Succeeded){
                        return RedirectToAction("Index");
                    }
                }
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            ViewBag.Roles = new MultiSelectList(roleManager.Roles.ToList(), "Name", "NormalizedName");
            var user = await userManager.FindByNameAsync(id);

            UserEditFormViewModel item = new UserEditFormViewModel();
            item.UserName = user.UserName;
            item.Email = user.Email;
            item.FullName = user.FullName;

            var roles = await userManager.GetRolesAsync(user);
            item.RoleID = roles.ToArray();

            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("UserName,RoleID,Email,Password,PasswordConfirm,FullName")] UserEditFormViewModel item)
        {
            ViewBag.Roles = new MultiSelectList(roleManager.Roles.ToList(), "Name", "NormalizedName");
            if (ModelState.IsValid) {
                ApplicationUser user = await userManager.FindByNameAsync(item.UserName);
                user.Email = item.Email;
                user.FullName = item.FullName;
                
                var existingRoles = await userManager.GetRolesAsync(user);
                IdentityResult result = await userManager.UpdateAsync(user);

                if (result.Succeeded) {
                    result = await userManager.RemoveFromRolesAsync(user, existingRoles);
                    if (result.Succeeded) {
                        result = await userManager.AddToRolesAsync(user, item.RoleID);
                        if (result.Succeeded) return RedirectToAction("Index");
                    }
                }
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (ModelState.IsValid) {
                var user = await userManager.FindByNameAsync(id);
                var result = await userManager.DeleteAsync(user);
                
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

Views/Shared/MasterLayout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <title>ASP.NET Core MVC: Book Store</title>

    <!-- Bootstrap -->
    <link href="~/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <!-- Font Awesome -->
    <link href="~/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet"/>
    <!-- NProgress -->
    <link href="~/vendors/nprogress/nprogress.css" rel="stylesheet"/>
    <!-- iCheck -->
    <link href="~/vendors/iCheck/skins/flat/green.css" rel="stylesheet"/>
	
    <!-- bootstrap-progressbar -->
    <link href="~/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet"/>
    <!-- JQVMap -->
    <link href="~/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="~/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet"/>

    <!-- Custom Theme Style -->
    <link href="~/build/css/custom.min.css" rel="stylesheet"/>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-book"></i> <span>Book Store</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="~/images/reza.jpg" alt="..." class="img-circle profile_img"/>
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>M Reza Faisal</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a asp-controller="Home" asp-action="Index">Dashboard</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-table"></i> Data <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a asp-controller="Category" asp-action="Index">Book Categories</a></li>
                      <li><a asp-controller="Author" asp-action="Index">Authors</a></li>
                      <li><a asp-controller="Book" asp-action="Index">Books</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-table"></i> Security <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a asp-controller="Role" asp-action="Index">Roles</a></li>
                      <li><a asp-controller="User" asp-action="Index">Users</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-bar-chart-o"></i> Reports <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#">Book by Category Chart</a></li>
                      <li><a href="#">Book Selling</a></li>
                    </ul>
                  </li>
                  </li>
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" asp-controller="Home" asp-action="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="~/images/reza.jpg" alt="">M Reza Faisal
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    <li>
                      <a href="javascript:;">
                        <span class="badge bg-red pull-right">50%</span>
                        <span>Settings</span>
                      </a>
                    </li>
                    <li><a href="javascript:;">Help</a></li>
                    <li><a asp-controller="Home" asp-action="Logout"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                  </ul>
                </li>

                <li role="presentation" class="dropdown">
                  <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-green">6</span>
                  </a>
                  <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                    <li>
                      <a>
                        <span class="image"><img src="~/images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="~/images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="~/images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <a>
                        <span class="image"><img src="~/images/img.jpg" alt="Profile Image" /></span>
                        <span>
                          <span>John Smith</span>
                          <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                          Film festivals used to be do-or-die moments for movie makers. They were where...
                        </span>
                      </a>
                    </li>
                    <li>
                      <div class="text-center">
                        <a>
                          <strong>See All Alerts</strong>
                          <i class="fa fa-angle-right"></i>
                        </a>
                      </div>
                    </li>
                  </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->
		
		
		<!-- -------------------------------------------------------------------------------------------- -->
		<!-- page content -->
    <div class="right_col" role="main">
		@RenderBody()
		</div>
		<!-- /page content -->
		<!-- -------------------------------------------------------------------------------------------- -->
		
		<!-- footer content -->
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="~/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="~/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="~/vendors/Chart.js/dist/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="~/vendors/gauge.js/dist/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="~/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="~/vendors/iCheck/icheck.min.js"></script>
    <!-- Skycons -->
    <script src="~/vendors/skycons/skycons.js"></script>
    <!-- Flot -->
    <script src="~/vendors/Flot/jquery.flot.js"></script>
    <script src="~/vendors/Flot/jquery.flot.pie.js"></script>
    <script src="~/vendors/Flot/jquery.flot.time.js"></script>
    <script src="~/vendors/Flot/jquery.flot.stack.js"></script>
    <script src="~/vendors/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="~/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="~/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="~/vendors/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="~/vendors/DateJS/build/date.js"></script>
    <!-- JQVMap -->
    <script src="~/vendors/jqvmap/dist/jquery.vmap.js"></script>
    <script src="~/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
    <script src="~/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="~/vendors/moment/min/moment.min.js"></script>
    <script src="~/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="~/build/js/custom.min.js"></script>
	
  </body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PgBookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PgBookStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PgBookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>