Controllers/LatihanController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using PgBookStore.Data;

namespace PgBookStore.Controllers
{
    public class LatihanController : Controller
    {
        private readonly ApplicationDbContext db;

        public LatihanController(ApplicationDbContext dbContext)
        {
            db = dbContext;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Template()
        {
            ViewBag.Authors = db.Authors.ToList();
            return View();
        }
    }
}

Views/Latihan/Index.cshtml
@{
    Layout = "MasterLayout";
}
@model PgBookStore.Models.ContohAtributModel

<h1>Contoh Attribute Model</h1>
<form asp-controller="Latihan" asp-action="Attribut">
    <label asp-for="ContohEmail"></label>
    <input asp-for="ContohEmail"/>
    <br/>

    <label asp-for="ContohUrl"></label>
    <input asp-for="ContohUrl"/>
    <br/>

    <label asp-for="ContohPhone"></label>
    <input asp-for="ContohPhone"/>
    <br/>

    <label asp-for="ContohPassword"></label>
    <input asp-for="ContohPassword"/>
    <br/>

    <label asp-for="ContohDate"></label>
    <input asp-for="ContohDate"/>
    <br/>

    <label asp-for="ContohTime"></label>
    <input asp-for="ContohTime"/>
    <br/>

    <button type="submit" class="btn btn-success">Submit</button>
</form>

Views/Latihan/Template.cshtml
@{
    Layout = "MasterLayout";
}
@model PgBookStore.Models.ContohModel

<h1>Contoh Attribute Model</h1>
<form asp-controller="Latihan" asp-action="Attribut">
    <label asp-for="ContohText" class="control-label"></label>
    <select asp-for="ContohText" asp-items="@(new SelectList(ViewBag.Authors, "AuthorID","Name"))" class="form-control">
        <option>Choose Authors</option>
    </select>
    <button type="submit" class="btn btn-success">Submit</button>
</form>